[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 9600

lib_deps =
    adafruit/DHT sensor library@^1.4.4
    knolleary/PubSubClient@^2.8
